services:
  audio-bot-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "${VITE_API_BASE_URL}"
        VITE_LIVEKIT_URL: "${VITE_LIVEKIT_URL}"
    container_name: audio-bot-front
    ports:
      - "7777:80"
    environment:
      - NODE_ENV=production
    networks:
      - audio-bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  audio-bot-network:
    external: true 